encrypt = str(input("Enter msg: "))
FLAG = f"{encrypt}".encode()
#FLAG = b"w1ntr{test flag aja duluAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}"